services:
  database:
    container_name: database
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=guest'
      - 'POSTGRES_DB=Biblioteca'
      - 'POSTGRES_PASSWORD=guest'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql