CREATE TYPE status AS ENUM ('AVAILABLE', 'UNAVAILABLE');

CREATE TABLE tbuser (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	active BOOLEAN NOT NULL
);

CREATE TABLE tbbook (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	resume TEXT,
	release_date DATE,
	genre VARCHAR(100),
	author VARCHAR(255),
	status status NOT NULL,
	active BOOLEAN NOT NULL
);