spring:
  profiles:
    active: dev
  application:
    name: biblioteca
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca&useSSL=false
    username: guest
    password: guest
    driver-class: org.postgresql.Driver

server:
  port: 3000