version: '3'

services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=guest'
      - 'POSTGRES_DB=biblioteca'
      - 'POSTGRES_PASSWORD=guest'