openapi: 3.0.4
info:
  title: Sample Pet Store App
  version: 1.0.0
  description: This is a sample server for a pet store.
servers:
  - url: http://localhost:3001/v1
paths:
  /example:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []